### ISSUE TITLE
Update shadow-utils RPM to create subuid and subgid files.

### ISSUE THREAD

**Issue by CtrlC-Root** [CtrlC-Root/rpmdist#2]
The shadow-utils RPM should create initial `/etc/subuid` and `/etc/subgid` files so the `usermod --add-subuids` and `usermod --add-subgids` commands work out of the box. The files should probably include a header that documents their format in a comment and should be marked as configuration files so they aren't overwritten on a package upgrade.

**Comment by CtrlC-Root** [comment]
Some random documentation here: http://lists.linuxfoundation.org/pipermail/containers/2013-January/031635.html.

**Comment by mliudev** [comment]
I'm having some trouble figuring out why the files aren't appearing when I do a `mock --rebuild shadow-utils-4.2.1-4.el7.centos.src.rpm` with the updated spec file. I created the subuid and subgid files and dropped them in the shadow-utils spec folder. Then I modified the spec file to include the two files as sources and install them to the sysconfig directory. However, when I do a `mock --shell` and do a find for the files they are not in `/etc`.

I've pushed my branch if you want to take a look.

**Comment by mliudev** [comment]
Actually I think this might already be working. I think I might be misunderstanding what `mock --rebuild` does. I don't think it actually installs the SRPM that I've made. It installs the original and then builds the SRPM off of it.

**Comment by CtrlC-Root** [comment]
Yeah, it looks like it would work to me. I'll build the RPM to verify it works when you create a pull request. One minor change I think you should make though is to change the first comment in the files to document the format of the columns. Take a look at this part of the link I posted above for an explanation of the format:

```
+    <para>
+      Each line in <filename>/etc/subgid</filename> contains
+      a user id and a range of suboridinate user ids that user
+      is allowed to use.
+
+      This is specified with three fields delimited by colons
+      (<quote>:</quote>).
+      These fields are:
+    </para>
+    <itemizedlist mark='bullet'>
+      <listitem>
+	<para>login name</para>
+      </listitem>
+      <listitem>
+	<para>numerical subordinate user ID</para>
+      </listitem>
+      <listitem>
+	<para>numerical subordinate user ID count</para>
+      </listitem>
+    </itemizedlist>
+
```

**Comment by mliudev** [comment]
Yup I planned on it. Just wanted you to take a look first at what I might have been doing wrong.
